### ISSUE TITLE
Error 500 with new install

### ISSUE THREAD

**Issue by ulysserevient** [Leantime/docker-leantime#74]
Hi,
I'm fully unable toi install Leantime with Dockerc-compose.
After starting containers, I obtain error 500 and this log : 

`Creating configuration file!
2024-04-02 19:19:15,396 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2024-04-02 19:19:15,398 INFO supervisord started with pid 10
2024-04-02 19:19:16,399 INFO spawned: 'php-fpm' with pid 11
2024-04-02 19:19:16,401 INFO spawned: 'httpd' with pid 12
[02-Apr-2024 19:19:16] NOTICE: fpm is running, pid 11
[02-Apr-2024 19:19:16] NOTICE: ready to handle connections
2024-04-02 19:19:17,421 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-04-02 19:19:17,421 INFO success: httpd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
NOTICE: PHP message: PHP Warning:  file_put_contents(/var/www/html/cache/installation/c6/92/c692273deb2772da307ffe37041fef77bf4baa97): Failed to open stream: No such file or directory in /var/www/html/vendor/illuminate/filesystem/Filesystem.php on line 190
NOTICE: PHP message: PHP Warning:  file_put_contents(/var/www/html/cache/installation/5b/ac/5bac1d3aee24b76ccad2a413c6a76d4780014219): Failed to open stream: No such file or directory in /var/www/html/vendor/illuminate/filesystem/Filesystem.php on line 190
NOTICE: PHP message: PHP Warning:  file_put_contents(/var/www/html/cache/views/abcad8e5a22bd29aaabbc2b51e223bacc196be9c.php): Failed to open stream: Permission denied in /var/www/html/vendor/illuminate/filesystem/Filesystem.php on line 190
NOTICE: PHP message: Illuminate\Contracts\Filesystem\FileNotFoundException: File does not exist at path /var/www/html/cache/views/abcad8e5a22bd29aaabbc2b51e223bacc196be9c.php. in /var/www/html/vendor/illuminate/filesystem/Filesystem.php:113

Stack trace:
#0 /var/www/html/vendor/illuminate/view/Engines/PhpEngine.php(58): Illuminate\Filesystem\Filesystem->getRequire('/var/www/html/c...', Array)
#1 /var/www/html/vendor/illuminate/view/Engines/CompilerEngine.php(70): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/html/c...', Array)
#2 /var/www/html/vendor/illuminate/view/View.php(195): Illuminate\View\Engines\CompilerEngine->get('/var/www/html/a...', Array)
#3 /var/www/html/vendor/illuminate/view/View.php(178): Illuminate\View\View->getContents()
#4 /var/www/html/vendor/illuminate/view/View.php(147): Illuminate\View\View->renderContents()
#5 /var/www/html/app/Core/Template.php(509): Illuminate\View\View->render()
#6 /var/www/html/app/Domain/Install/Controllers/Index.php(41): Leantime\Core\Template->display('install.new', 'global::layouts...')
#7 /var/www/html/app/Core/Controller.php(82): Leantime\Domain\Install\Controllers\Index->get(Array)
#8 /var/www/html/app/Core/Controller.php(49): Leantime\Core\Controller->executeActions('GET', Array)
#9 [internal function]: Leantime\Core\Controller->__construct(Object(Leantime\Core\IncomingRequest), Object(Leantime\Core\Template), Object(Leantime\Core\Language))
#10 /var/www/html/vendor/illuminate/container/Container.php(929): ReflectionClass->newInstanceArgs(Array)
#11 /var/www/html/vendor/illuminate/container/Container.php(770): Illuminate\Container\Container->build('Leantime\\Domain...')
#12 /var/www/html/vendor/illuminate/container/Container.php(706): Illuminate\Container\Container->resolve('Leantime\\Domain...', Array)
#13 /var/www/html/app/Core/Frontcontroller.php(130): Illuminate\Container\Container->make('Leantime\\Domain...')
#14 /var/www/html/app/Core/Frontcontroller.php(75): Leantime\Core\Frontcontroller::executeAction('install', Array)
#15 /var/www/html/app/Core/HttpKernel.php(63): Leantime\Core\Frontcontroller::dispatch()
#16 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(141): Leantime\Core\HttpKernel->Leantime\Core\{closure}(Object(Leantime\Core\IncomingRequest))
#17 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#18 /var/www/html/app/Core/HttpKernel.php(63): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#19 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(141): Leantime\Core\HttpKernel->Leantime\Core\{closure}(Object(Leantime\Core\IncomingRequest))
#20 /var/www/html/app/Core/Middleware/CurrentProject.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#21 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\CurrentProject->handle(Object(Leantime\Core\IncomingRequest), Object(Closure))
#22 /var/www/html/app/Core/Middleware/Localization.php(48): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#23 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\Localization->handle(Object(Leantime\Core\IncomingRequest), Object(Closure))
#24 /var/www/html/app/Core/Middleware/Auth.php(74): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#25 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\Auth->handle(Object(Leantime\Core\IncomingRequest), Object(Closure))
#26 /var/www/html/app/Core/Middleware/Updated.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#27 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\Updated->handle(Object(Leantime\Core\IncomingRequest), Object(Closure))
#28 /var/www/html/app/Core/Middleware/Installed.php(31): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#29 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\Installed->handle(Object(Leantime\Core\IncomingRequest), Object(Closure))
#30 /var/www/html/app/Core/Middleware/InitialHeaders.php(22): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#31 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\InitialHeaders->handle(Object(Leantime\Core\IncomingRequest), Object(Closure))
#32 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#33 /var/www/html/app/Core/HttpKernel.php(64): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#34 /var/www/html/app/Core/Bootloader.php(303): Leantime\Core\HttpKernel->handle(Object(Leantime\Core\IncomingRequest))
#35 /var/www/html/app/Core/Bootloader.php(173): Leantime\Core\Bootloader->handleRequest()
#36 /var/www/html/public/index.php(18): Leantime\Core\Bootloader->boot()
#37 {main}
Next Illuminate\View\ViewException: File does not exist at path /var/www/html/cache/views/abcad8e5a22bd29aaabbc2b51e223bacc196be9c.php. (View: /var/www/html/app/Views/Templates/layouts/entry.blade.php) in /var/www/html/vendor/illuminate/filesystem/Filesystem.php:113

Stack trace:
#0 /var/www/html/vendor/illuminate/view/Engines/PhpEngine.php(60): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(Illuminate\Contracts\Filesystem\FileNotFoundException), 0)
#1 /var/www/html/vendor/illuminate/view/Engines/CompilerEngine.php(70): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/html/c...', Array)
#2 /var/www/html/vendor/illuminate/view/View.php(195): Illuminate\View\Engines\CompilerEngine->get('/var/www/html/a...', Array)
#3 /var/www/html/vendor/illuminate/view/View.php(178): Illuminate\View\View->getContents()
#4 /var/www/html/vendor/illuminate/view/View.php(147): Illuminate\View\View->renderContents()
#5 /var/www/html/app/Core/Template.php(509): Illuminate\View\View->render()
#6 /var/www/html/app/Domain/Install/Controllers/Index.php(41): Leantime\Core\Template->display('install.new', 'global::layouts...')
#7 /var/www/html/app/Core/Controller.php(82): Leantime\Domain\Install\Controllers\Index->get(Array)
#8 /var/www/html/app/Core/Controller.php(49): Leantime\Core\Controller->executeActions('GET', Array)
#9 [internal function]: Leantime\Core\Controller->__construct(Object(Leantime\Core\IncomingRequest), Object(Leantime\Core\Template), Object(Leantime\Core\Language))
#10 /var/www/html/vendor/illuminate/container/Container.php(929): ReflectionClass->newInstanceArgs(Array)
#11 /var/www/html/vendor/illuminate/container/Container.php(770): Illuminate\Container\Container->build('Leantime\\Domain...')
#12 /var/www/html/vendor/illuminate/container/Container.php(706): Illuminate\Container\Container->resolve('Leantime\\Domain...', Array)
#13 /var/www/html/app/Core/Frontcontroller.php(130): Illuminate\Container\Container->make('Leantime\\Domain...')
#14 /var/www/html/app/Core/Frontcontroller.php(75): Leantime\Core\Frontcontroller::executeAction('install', Array)
#15 /var/www/html/app/Core/HttpKernel.php(63): Leantime\Core\Frontcontroller::dispatch()
#16 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(141): Leantime\Core\HttpKernel->Leantime\Core\{closure}(Object(Leantime\Core\IncomingRequest))
#17 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#18 /var/www/html/app/Core/HttpKernel.php(63): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#19 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(141): Leantime\Core\HttpKernel->Leantime\Core\{closure}(Object(Leantime\Core\IncomingRequest))
#20 /var/www/html/app/Core/Middleware/CurrentProject.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Leantime\Core\IncomingRequest))
#21 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(180): Leantime\Core\Middleware\Current...
NOTICE: PHP message: PHP Warning:  file_put_contents(/var/www/html/cache/views/edf299eb4370dce66f71099b13d581c6da5749e0.php): Failed to open stream: Permission denied in /var/www/html/vendor/illuminate/filesystem/Filesystem.php on line 190
127.0.0.1 -  02/Apr/2024:19:19:42 +0000 "GET /index.php" 500
NOTICE: PHP message: PHP Fatal error:  Uncaught Illuminate\Contracts\Filesystem\FileNotFoundException: File does not exist at path /var/www/html/cache/views/edf299eb4370dce66f71099b13d581c6da5749e0.php. in /var/www/html/vendor/illuminate/filesystem/Filesystem.php:113

Stack trace:
#0 /var/www/html/vendor/illuminate/view/Engines/PhpEngine.php(58): Illuminate\Filesystem\Filesystem->getRequire('/var/www/html/c...', Array)
#1 /var/www/html/vendor/illuminate/view/Engines/CompilerEngine.php(70): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/html/c...', Array)
#2 /var/www/html/vendor/illuminate/view/View.php(195): Illuminate\View\Engines\CompilerEngine->get('/var/www/html/a...', Array)
#3 /var/www/html/vendor/illuminate/view/View.php(178): Illuminate\View\View->getContents()
#4 /var/www/html/vendor/illuminate/view/View.php(147): Illuminate\View\View->renderContents()
#5 /var/www/html/app/Core/Template.php(509): Illuminate\View\View->render()
#6 /var/www/html/app/Core/HttpKernel.php(77): Leantime\Core\Template->display('errors.error500', 'global::layouts...')
#7 /var/www/html/app/Core/Bootloader.php(303): Leantime\Core\HttpKernel->handle(Object(Leantime\Core\IncomingRequest))
#8 /var/www/html/app/Core/Bootloader.php(173): Leantime\Core\Bootloader->handleRequest()
#9 /var/www/html/public/index.php(18): Leantime\Core\Bootloader->boot()
#10 {main}
Next Illuminate\View\ViewException: File does not exist at path /var/www/html/cache/views/edf299eb4370dce66f71099b13d581c6da5749e0.php. (View: /var/www/html/app/Views/Templates/layouts/error.blade.php) in /var/www/html/vendor/illuminate/filesystem/Filesystem.php:113

Stack trace:
#0 /var/www/html/vendor/illuminate/view/Engines/PhpEngine.php(60): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(Illuminate\Contracts\Filesystem\FileNotFoundException), 0)
#1 /var/www/html/vendor/illuminate/view/Engines/CompilerEngine.php(70): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/html/c...', Array)
#2 /var/www/html/vendor/illuminate/view/View.php(195): Illuminate\View\Engines\CompilerEngine->get('/var/www/html/a...', Array)
#3 /var/www/html/vendor/illuminate/view/View.php(178): Illuminate\View\View->getContents()
#4 /var/www/html/vendor/illuminate/view/View.php(147): Illuminate\View\View->renderContents()
#5 /var/www/html/app/Core/Template.php(509): Illuminate\View\View->render()
#6 /var/www/html/app/Core/HttpKernel.php(77): Leantime\Core\Template->display('errors.error500', 'global::layouts...')
#7 /var/www/html/app/Core/Bootloader.php(303): Leantime\Core\HttpKernel->handle(Object(Leantime\Core\IncomingRequest))
#8 /var/www/html/app/Core/Bootloader.php(173): Leantime\Core\Bootloader->handleRequest()
#9 /var/www/html/public/index.php(18): Leantime\Core\Bootloader->boot()
#10 {main}
  thrown in /var/www/html/vendor/illuminate/filesystem/Filesystem.php on line 113`

Please could you help me ?

**Comment by michaelcheng0407** [comment]
I have the same issue.
run "chmod -R 777 /var/www/html" in the container solveed my problem

**Comment by ulysserevient** [comment]
Hi,
It works !!!
Thanks !

**Comment by typkrft** [comment]
I think this should really be re-opened. I ran into this on an upgrade and recursively opening all permissions feels a bit nuclear.

**Comment by FM-96** [comment]
I agree. @ulysserevient, please reopen this. This is a bug in the software, and it hasn't been fixed.

**Comment by michaelcheng0407** [comment]
I guess similar issue Leantime/leantime#2454.
They suggested "chown www-data:www-data -R /var/www/html/cache"

**Comment by marcelfolaron** [comment]
Hi All,

I went ahead and updated the permissions as part of the Dockerfile and that should fix the issue. Both latest and :3.1.1 were recreated with the new settings.
